#!/bin/bash

# get year, language, day(s), and test flag from the terminal input
year=$1
language=$2
days=$3
test_flag=$4


if [ "$language" == "-p" ]; then
  path="./AdventOfCode$year/main.py"
  time python3 $path $days $test_flag

elif [ "$language" == "-c" ]; then
  path="./AdventOfCode$year/main.c"
  helper_path="./AdventOfCode$year/helper.c"
  solution_path="./AdventOfCode$year/c_solutions/*.c"
  gcc $path $helper_path $solution_path -o build/main_c

  # run c executable
  ./build/main_c
  rm ./build/main_c

elif [ "$language" == "-cpp" ]; then
  path="./AdventOfCode$year/main.cpp"
  helper_path="./AdventOfCode$year/helper.cpp"
  solution_path="./AdventOfCode$year/c++_solutions/*.cpp"
  g++ -std=c++11 $path $helper_path $solution_path -o build/main_cpp

  # run cpp executable
  ./build/main_cpp $days $test_flag
  rm ./build/main_cpp
fi